# Generated by Django 4.0.1 on 2022-02-02 18:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('mother_language', models.CharField(choices=[('1_Arabic', 'العربية'), ('2_English', 'الأنجليزية'), ('3_French', 'الفرنسية'), ('4_Spanish', 'الأسبانية')], max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('field_concern', models.CharField(blank=True, choices=[('كتب عامة', 'كتب عامة'), ('إدارة وأعمال', 'إدارة وأعمال'), ('أدب وشعر', 'أدب وشعر'), ('أطفال', 'أطفال'), ('أكاديمية', 'أكاديمية'), ('تراجم وسير', 'تراجم وسير'), ('طب وصحة', 'طب وصحة'), ('تطوير ذات ', 'تطوير ذات '), ('قصص وروايات', 'قصص وروايات'), ('كتب دينية', 'كتب دينية'), ('كتب صوتية', 'كتب صوتية')], max_length=255)),
                ('about_you', ckeditor.fields.RichTextField(null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
