# Generated by Django 4.0.1 on 2022-02-02 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_userprofile_source_userprofile_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('is_open_download', models.BooleanField(default=False, null=True)),
                ('book_cover', models.ImageField(upload_to='covers/')),
                ('book_address', models.CharField(blank=True, max_length=250, null=True)),
                ('book_language', models.CharField(blank=True, choices=[('اللغة العربية', 'اللغة العربية'), ('اللغة الإنجليزية', 'اللغة الإنجليزية'), ('اللغة الفرنسية', 'اللغة الفرنسية'), ('اللغة الألمانية', 'اللغة الألمانية'), ('اللغة الروسية', 'اللغة الروسية'), ('اللغة اليابانية', 'اللغة اليابانية'), ('اللغة الصينية', 'اللغة الصينية')], max_length=200)),
                ('translate_language', models.CharField(blank=True, choices=[('اللغة العربية', 'اللغة العربية'), ('اللغة الإنجليزية', 'اللغة الإنجليزية'), ('اللغة الفرنسية', 'اللغة الفرنسية'), ('اللغة الألمانية', 'اللغة الألمانية'), ('اللغة الروسية', 'اللغة الروسية'), ('اللغة اليابانية', 'اللغة اليابانية'), ('اللغة الصينية', 'اللغة الصينية')], max_length=200)),
                ('pages_number', models.IntegerField(blank=True, null=True)),
                ('translator_number', models.SmallIntegerField(blank=True, null=True)),
                ('translator_fees', models.IntegerField(blank=True, null=True)),
                ('project_time', models.CharField(blank=True, choices=[('شهرين', 'شهرين'), ('ثلاث أشهر', 'ثلاث أشهر'), ('ستة أشهر', 'ستة أشهر')], max_length=200)),
                ('book_category', models.CharField(choices=[('كتب عامة', 'كتب عامة'), ('إدارة وأعمال', 'إدارة وأعمال'), ('أدب وشعر', 'أدب وشعر'), ('أطفال', 'أطفال'), ('أكاديمية', 'أكاديمية'), ('تراجم وسير', 'تراجم وسير'), ('تطوير ذات', 'تطوير ذات'), ('طب وصحة', 'طب وصحة'), ('قصص وروايات', 'قصص وروايات'), ('كتب دينية', 'كتب دينية')], max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
