# Generated by Django 4.0.1 on 2022-02-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontract',
            name='is_entered',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bookcontract',
            name='is_accepted',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True),
        ),
        migrations.CreateModel(
            name='BookVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('first_pay', models.CharField(choices=[('تم الدفع', 'تم الدفع'), ('لم الدفع', 'لم الدفع')], max_length=255, null=True)),
                ('second_pay', models.CharField(choices=[('تم الدفع', 'تم الدفع'), ('لم الدفع', 'لم الدفع')], max_length=255, null=True)),
                ('third_pay', models.CharField(choices=[('تم الدفع', 'تم الدفع'), ('لم الدفع', 'لم الدفع')], max_length=255, null=True)),
                ('first_received', models.DateField(null=True)),
                ('second_received', models.DateField(null=True)),
                ('third_received', models.DateField(null=True)),
                ('is_completed', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], null=True)),
                ('is_sent', models.BooleanField(choices=[(True, 'نعم'), (False, 'لا')], null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookcontract')),
            ],
        ),
    ]
