# Generated by Django 4.0.1 on 2022-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_option',
            field=models.SmallIntegerField(choices=[(1, 'بيع حقوق نشر'), (2, 'بيع حقوق ترجمة')], null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='dropbox_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
