# Generated by Django 4.0.1 on 2022-03-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_publisherneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherneeds',
            name='needs',
            field=models.CharField(blank=True, choices=[('مدقق لغوى', 'مدقق لغوى'), ('مترجم ', ' مترجم'), ('مصمم ', ' مصمم')], max_length=255, null=True),
        ),
    ]
