# Generated by Django 4.0.1 on 2022-03-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_option',
            field=models.SmallIntegerField(choices=[(1, 'إعلان'), (2, 'بيع حقوق كتاب')], null=True),
        ),
    ]
