# Generated by Django 4.0.1 on 2022-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_book_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDistrubuting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('auther_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('number_of_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('distrub_choices', models.CharField(choices=[('ورقى', 'ورقى'), ('إلكتروني', 'إلكتروني')], max_length=255)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('book_price', models.SmallIntegerField(blank=True, null=True)),
                ('about_book', models.TextField(blank=True, null=True)),
                ('time_finish', models.CharField(blank=True, max_length=255, null=True)),
                ('author_rights', models.CharField(blank=True, max_length=255, null=True)),
                ('auther_profit', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_copies', models.CharField(blank=True, max_length=255, null=True)),
                ('time_own', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_option',
        ),
    ]
