# Generated by Django 4.0.1 on 2022-03-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_negotiation_time_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pay_chocies',
            field=models.CharField(blank=True, choices=[('عمل خيرى', 'عمل خيرى'), ('عمل مدفوع', 'عمل مدفوع')], max_length=255, null=True),
        ),
    ]
