# Generated by Django 4.0.1 on 2022-03-15 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0019_alter_foundtationuserprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundtationuserprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
