# Generated by Django 4.0.1 on 2022-03-15 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0021_alter_foundtationuserprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontract',
            name='found',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_book_contract', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookcontract',
            name='author_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_book_contract', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookcontract',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_contract', to='books.book'),
        ),
        migrations.CreateModel(
            name='CopyRightContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('contract', models.FileField(upload_to='contract-copyright/')),
                ('is_accepted', models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True)),
                ('is_entered', models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_contracts', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_rights_found_contracts', to='books.bookdistrubuting')),
                ('found', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
