# Generated by Django 4.0.1 on 2022-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_bookcontract_found_alter_bookcontract_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherneeds',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisherneeds',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='publisherneeds',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publisherneeds',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
