# Generated by Django 4.0.1 on 2022-03-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_publisherneeds_duration_publisherneeds_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherneeds',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
