# Generated by Django 4.0.1 on 2022-03-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_publisherneeds_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
        migrations.AddField(
            model_name='book',
            name='book_content',
            field=models.FileField(null=True, upload_to='books/'),
        ),
    ]
