# Generated by Django 4.0.1 on 2022-03-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_alter_book_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtationuserprofile',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
