# Generated by Django 4.0.1 on 2022-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_needspresent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherneeds',
            name='needs',
            field=models.CharField(blank=True, choices=[('مدقق لغوى', 'مدقق لغوى'), ('مترجم ', ' مترجم'), ('مصمم ', ' مصمم'), ('كاتب ', ' كاتب')], max_length=255, null=True),
        ),
    ]
