# Generated by Django 4.0.1 on 2022-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_alter_publisherneeds_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontract',
            name='contract',
            field=models.ImageField(upload_to='contract/'),
        ),
        migrations.AlterField(
            model_name='copyrightcontract',
            name='contract',
            field=models.ImageField(upload_to='contract-copyright/'),
        ),
    ]
