# Generated by Django 4.0.1 on 2022-03-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_negotiationbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='is_accepted',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='negotiationbook',
            name='is_accepted',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True),
        ),
    ]
