# Generated by Django 4.0.1 on 2022-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_foundtationuserprofile_art_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtationuserprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
