# Generated by Django 4.0.1 on 2022-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_foundtationuserprofile_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creaditCard_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
