# Generated by Django 4.0.1 on 2022-03-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_userprofile_creaditcard_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiationbook',
            name='author_ratio',
        ),
        migrations.RemoveField(
            model_name='negotiationbook',
            name='author_rights',
        ),
        migrations.RemoveField(
            model_name='negotiationbook',
            name='number_of_copies',
        ),
        migrations.AddField(
            model_name='negotiationbook',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
