# Generated by Django 4.0.1 on 2022-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_remove_negotiationbook_author_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundtationuserprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foundtationuserprofile',
            name='creaditCard_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
