# Generated by Django 4.0.1 on 2022-04-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_foundtationuserprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationbook',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
