# Generated by Django 4.0.1 on 2022-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0041_negotiationbook_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontract',
            name='contract_signed',
            field=models.FileField(blank=True, null=True, upload_to='contract-signed/'),
        ),
        migrations.AlterField(
            model_name='bookcontract',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract/'),
        ),
    ]
