# Generated by Django 4.0.1 on 2022-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0043_copyrightcontract_contract_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontract',
            name='is_signed',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='copyrightcontract',
            name='is_signed',
            field=models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True),
        ),
    ]
