# Generated by Django 4.0.1 on 2022-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_bookcontract_is_signed_copyrightcontract_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_shown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
