# Generated by Django 4.0.1 on 2022-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text_file', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, choices=[('اللغة العربية', 'اللغة العربية'), ('اللغة الإنجليزية', 'اللغة الإنجليزية')], max_length=255, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('filed', models.CharField(blank=True, choices=[('مجال عام', 'مجال عام'), ('مجال سياسي', 'مجال سياسي'), ('مجال اقتصادي', 'مجال اقتصادي'), ('مجال أكاديمي', 'مجال أكاديمي'), ('مجال ديني', 'مجال ديني')], max_length=255, null=True)),
                ('translate_to', models.CharField(blank=True, choices=[('عربي – انجليزي', 'عربي – انجليزي'), ('انجليزي - عربي', 'انجليزي - عربي')], max_length=255, null=True)),
                ('finish_hours', models.CharField(blank=True, choices=[('ساعة', 'ساعة'), ('اربع ساعات', 'اربع ساعات')], max_length=255, null=True)),
            ],
        ),
    ]
