# Generated by Django 4.0.1 on 2022-02-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designservice',
            name='filed',
            field=models.CharField(blank=True, choices=[('مجال عام', 'مجال عام'), ('مجال سياسي', 'مجال سياسي'), ('مجال اقتصادي', 'مجال اقتصادي'), ('مجال أكاديمي', 'مجال أكاديمي'), ('مجال ديني', 'مجال ديني')], max_length=255, null=True, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='designservice',
            name='finish_hours',
            field=models.CharField(blank=True, choices=[('ساعة', 'ساعة'), ('اربع ساعات', 'اربع ساعات')], max_length=255, null=True, verbose_name='Time to finish'),
        ),
        migrations.AlterField(
            model_name='designservice',
            name='language',
            field=models.CharField(blank=True, choices=[('اللغة العربية', 'اللغة العربية'), ('اللغة الإنجليزية', 'اللغة الإنجليزية')], max_length=255, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='designservice',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of pages'),
        ),
        migrations.AlterField(
            model_name='designservice',
            name='text_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text File'),
        ),
        migrations.AlterField(
            model_name='designservice',
            name='translate_to',
            field=models.CharField(blank=True, choices=[('عربي – انجليزي', 'عربي – انجليزي'), ('انجليزي - عربي', 'انجليزي - عربي')], max_length=255, null=True, verbose_name='Translate to'),
        ),
    ]
