# Generated by Django 4.0.1 on 2022-02-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_designservice_text_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignService',
            new_name='TranslateService',
        ),
    ]
