# Generated by Django 4.0.1 on 2022-02-23 18:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_designservice_translateservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDesignService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('book_size', models.CharField(blank=True, max_length=255, null=True)),
                ('title_book', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('translator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('version_number', models.CharField(blank=True, max_length=255, null=True)),
                ('house_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('about_book', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn_number', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn_bar', models.CharField(blank=True, max_length=255, null=True)),
                ('house_info', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('communication', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('note', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
