# Generated by Django 4.0.1 on 2022-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_requestdesignservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdesignservice',
            name='author_name_tail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdesignservice',
            name='part_number_tail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdesignservice',
            name='scientific_rank_tail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdesignservice',
            name='translator_name_tail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestdesignservice',
            name='version_number_tail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
