# Generated by Django 4.0.1 on 2022-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_requestdesignservice_author_name_tail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdesignservice',
            name='communication',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
