# Generated by Django 4.0.1 on 2022-02-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_requestdesignservice_communication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdesignservice',
            name='isbn_bar',
        ),
    ]
