# Generated by Django 4.0.1 on 2022-02-26 18:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_requestdesignservice_isbn_bar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdesignservice',
            name='about_book',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
