# Generated by Django 4.0.1 on 2022-02-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_requestdesignservice_about_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdesignservice',
            name='is_shown_designer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
