# Generated by Django 4.0.1 on 2022-03-01 19:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_requestdesignservice_is_shown_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProofReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('about_book', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_shown', models.BooleanField(blank=True, default=False, null=True)),
                ('user_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
