# Generated by Django 4.0.1 on 2022-03-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_vouchers_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchers',
            name='is_paid',
            field=models.BooleanField(blank=True, choices=[(True, 'تم الدفع'), (False, 'لم يتم الدفع ')], default=False, null=True),
        ),
        migrations.CreateModel(
            name='PaidVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('date', models.DateField(auto_now_add=True)),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.vouchers')),
            ],
        ),
    ]
