# Generated by Django 4.0.1 on 2022-03-09 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0014_alter_vouchers_is_paid_paidvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='get_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
