# Generated by Django 4.0.1 on 2022-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_vouchers_get_paid_alter_vouchers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('translator_introduction', models.CharField(blank=True, max_length=255, null=True)),
                ('dedication_page', models.CharField(blank=True, max_length=255, null=True)),
                ('thank_you_page', models.CharField(blank=True, max_length=255, null=True)),
                ('define_page', models.CharField(blank=True, max_length=255, null=True)),
                ('intro_page', models.CharField(blank=True, max_length=255, null=True)),
                ('content_pages', models.CharField(blank=True, max_length=255, null=True)),
                ('source_page', models.CharField(blank=True, max_length=255, null=True)),
                ('supplements_page', models.CharField(blank=True, max_length=255, null=True)),
                ('page_images', models.CharField(blank=True, max_length=255, null=True)),
                ('draws_page', models.CharField(blank=True, max_length=255, null=True)),
                ('CMYK_page', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('contact', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
