# Generated by Django 4.0.1 on 2022-03-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_pay_chocies'),
        ('services', '0016_translationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
