# Generated by Django 4.0.1 on 2022-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_translationrequest_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateservice',
            name='finish_hours',
            field=models.IntegerField(blank=True, choices=[(6, '6 ساعات'), (24, '24 ساعات'), (72, '72 ساعات'), (100, ' أسبوع او أكثر')], null=True, verbose_name='Time to finish'),
        ),
    ]
