# Generated by Django 4.0.1 on 2022-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_translateservice_finish_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text_file', models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Text File')),
                ('language', models.CharField(blank=True, choices=[('اللغة العربية', 'اللغة العربية'), ('اللغة الإنجليزية', 'اللغة الإنجليزية')], max_length=255, null=True, verbose_name='Language')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Url of Video')),
                ('filed', models.CharField(blank=True, choices=[('مجال عام', 'مجال عام'), ('مجال سياسي', 'مجال سياسي'), ('مجال اقتصادي', 'مجال اقتصادي'), ('مجال أكاديمي', 'مجال أكاديمي'), ('مجال ديني', 'مجال ديني')], max_length=255, null=True, verbose_name='Field')),
                ('translate_to', models.CharField(blank=True, choices=[('عربي – انجليزي', 'عربي – انجليزي'), ('انجليزي - عربي', 'انجليزي - عربي')], max_length=255, null=True, verbose_name='Translate to')),
                ('finish_hours', models.IntegerField(blank=True, null=True, verbose_name='Time to finish')),
            ],
        ),
    ]
