# Generated by Django 4.0.1 on 2022-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_contactrequestservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequestservices',
            name='time_sent',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
