# Generated by Django 4.0.1 on 2022-03-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_contactrequestservices_time_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='table_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
