# Generated by Django 4.0.1 on 2022-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_subtitleservice_subtitle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('publisher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('year_published', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('translator_cv', models.FileField(null=True, upload_to='requested-cv/')),
            ],
        ),
    ]
