# Generated by Django 4.0.1 on 2022-04-16 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0029_requestbook_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('author_rights', models.CharField(blank=True, max_length=255, null=True)),
                ('author_ratio', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_copies', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('time_finish', models.CharField(blank=True, max_length=255, null=True)),
                ('is_accepted', models.BooleanField(blank=True, choices=[(True, 'نعم'), (False, 'لا')], default=False, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.requestbook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
