# Generated by Django 4.0.1 on 2022-04-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_remove_negotiationrequests_author_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequests',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
