# Generated by Django 4.0.1 on 2022-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_negotiationrequests_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='translator_cv',
            field=models.FileField(blank=True, null=True, upload_to='requested-cv/'),
        ),
    ]
