# Generated by Django 4.0.1 on 2022-02-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_publisher',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a publisher. ', verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_translator',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as an Secondary Employee. ', verbose_name='translator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'أدمن'), (2, 'دار نشر'), (3, 'مترجم'), (4, 'مدقق لغوي'), (5, 'مصمم')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
