# Generated by Django 4.0.1 on 2022-02-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_publisher_alter_user_is_translator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'دار نشر'), (3, 'مترجم'), (4, 'مدقق لغوي'), (5, 'مصمم')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
