# Generated by Django 4.0.1 on 2022-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_designer',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a publisher. ', verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'أدمن'), (2, 'دار نشر'), (3, 'مترجم'), (4, 'مدقق لغوي'), (5, 'مصمم'), (6, 'كاتب'), (7, 'مطبعة'), (8, 'طالب خدمة')], help_text='User Role in A system ', null=True, verbose_name='User Type'),
        ),
    ]
