# Generated by Django 4.0.1 on 2022-03-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_designer_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_printer',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a Request Service. ', verbose_name='Printer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_proof_reader',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a Proof Reader. ', verbose_name='Proof Reader'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_request_service',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a Request Service. ', verbose_name='Request Service'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a Request Service. ', verbose_name='Writer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_designer',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a Designer. ', verbose_name='Designer'),
        ),
    ]
