# Generated by Django 4.0.1 on 2022-02-02 21:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_en', models.CharField(help_text='Title for Privacy Page [English]', max_length=255, null=True)),
                ('heading_ar', models.CharField(help_text='Title for Privacy Page [Arabic]', max_length=255, null=True)),
                ('sub_heading_en', models.CharField(help_text='SubTitle for Privacy Page [English]', max_length=255, null=True)),
                ('sub_heading_ar', models.CharField(help_text='SubTitle for Privacy Page [Arabic]', max_length=255, null=True)),
                ('section_one_en', ckeditor.fields.RichTextField(help_text='Section one for Privacy Page [English]', null=True)),
                ('section_one_ar', ckeditor.fields.RichTextField(help_text='Section one for Privacy Page [Arabic]', null=True)),
                ('section_two_en', ckeditor.fields.RichTextField(help_text='Section two for Privacy Page [English]', null=True)),
                ('section_two_ar', ckeditor.fields.RichTextField(help_text='Section two for Privacy Page [Arabic]', null=True)),
                ('section_three_en', ckeditor.fields.RichTextField(help_text='Section three for Privacy Page [English]', null=True)),
                ('section_three_ar', ckeditor.fields.RichTextField(help_text='Section three for Privacy Page [Arabic]', null=True)),
                ('section_four_en', ckeditor.fields.RichTextField(help_text='Section four for Privacy Page [English]', null=True)),
                ('section_four_ar', ckeditor.fields.RichTextField(help_text='Section four for Privacy Page [Arabic]', null=True)),
                ('section_five_en', ckeditor.fields.RichTextField(help_text='Section five for Privacy Page [English]', null=True)),
                ('section_five_ar', ckeditor.fields.RichTextField(help_text='Section five for Privacy Page [Arabic]', null=True)),
                ('section_six_en', ckeditor.fields.RichTextField(help_text='Section six for Privacy Page [English]', null=True)),
                ('section_six_ar', ckeditor.fields.RichTextField(help_text='Section six for Privacy Page [Arabic]', null=True)),
                ('section_seven_en', ckeditor.fields.RichTextField(help_text='Section seven for Privacy Page [English]', null=True)),
                ('section_seven_ar', ckeditor.fields.RichTextField(help_text='Section seven for Privacy Page [Arabic]', null=True)),
            ],
        ),
    ]
