# Generated by Django 4.0.1 on 2022-02-02 22:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roaya_heading_en', models.CharField(help_text='Title for Roaya Section [English]', max_length=255, null=True)),
                ('roaya_heading_ar', models.CharField(help_text='Title for Roaya Section [Arabic]', max_length=255, null=True)),
                ('roaya_sub_en', models.CharField(help_text='SubTitle for Roaya Section [English]', max_length=255, null=True)),
                ('roaya_sub_ar', models.CharField(help_text='SubTitle for Roaya Section [Arabic]', max_length=255, null=True)),
                ('section_roaya_en', ckeditor.fields.RichTextField(help_text='Section for Roaya Page [English]', null=True)),
                ('section_roaya_ar', ckeditor.fields.RichTextField(help_text='Section for Roaya Page [Arabic]', null=True)),
                ('goals_heading_en', models.CharField(help_text='Title for goals Section [English]', max_length=255, null=True)),
                ('goals_heading_ar', models.CharField(help_text='Title for goals Section [Arabic]', max_length=255, null=True)),
                ('goals_sub_en', models.CharField(help_text='SubTitle for goals Section [English]', max_length=255, null=True)),
                ('goals_sub_ar', models.CharField(help_text='SubTitle for goals Section [Arabic]', max_length=255, null=True)),
                ('section_goals_en', ckeditor.fields.RichTextField(help_text='Section for goals Page [English]', null=True)),
                ('section_goals_ar', ckeditor.fields.RichTextField(help_text='Section for goals Page [Arabic]', null=True)),
                ('roles_heading_en', models.CharField(help_text='Title for roles Section [English]', max_length=255, null=True)),
                ('roles_heading_ar', models.CharField(help_text='Title for roles Section [Arabic]', max_length=255, null=True)),
                ('roles_sub_en', models.CharField(help_text='SubTitle for roles Section [English]', max_length=255, null=True)),
                ('roles_sub_ar', models.CharField(help_text='SubTitle for roles Section [Arabic]', max_length=255, null=True)),
                ('section_roles_en', ckeditor.fields.RichTextField(help_text='Section for roles Page [English]', null=True)),
                ('section_roles_ar', ckeditor.fields.RichTextField(help_text='Section for roles Page [Arabic]', null=True)),
            ],
        ),
    ]
