# Generated by Django 4.0.1 on 2022-02-04 16:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_membershipterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_we_offer_en', models.CharField(help_text='Title for What we offers section [English]', max_length=255, null=True)),
                ('what_we_offer_ar', models.CharField(help_text='Title for What we offers section  [Arabic]', max_length=255, null=True)),
                ('what_we_offer_sub_en', models.CharField(help_text='Subitle for What we offers section [English]', max_length=255, null=True)),
                ('what_we_offer_sub_ar', models.CharField(help_text='Subitle for What we offers section  [Arabic]', max_length=255, null=True)),
                ('what_we_offer_btn_txt_en', models.CharField(help_text='text for button in What we offers section [English]', max_length=255, null=True)),
                ('what_we_offer_btn_txt_ar', models.CharField(help_text='text for button in What we offers section [Arabic]', max_length=255, null=True)),
                ('service_one_title_en', models.CharField(choices=[('Cover design', 'Cover design'), ('Book format', 'Book format'), ('Subtraction', 'Subtraction'), ('Audio transcription', 'Audio transcription')], help_text='Title for Services section [English]', max_length=255, null=True)),
                ('service_one_title_ar', models.CharField(choices=[('تصميم الغلاف', 'تصميم الغلاف'), ('تنسيق الكتاب', 'تنسيق الكتاب'), ('السترجة', 'السترجة'), ('النسخ الصوتى', 'النسخ الصوتى')], help_text='Title for Services section  [Arabic]', max_length=255, null=True)),
                ('service_one_summary_en', ckeditor.fields.RichTextField(help_text='Summary Services section [English]', null=True)),
                ('service_one_summary_ar', ckeditor.fields.RichTextField(help_text='Summary for Services section  [Arabic]', null=True)),
                ('service_two_title_en', models.CharField(choices=[('Cover design', 'Cover design'), ('Book format', 'Book format'), ('Subtraction', 'Subtraction'), ('Audio transcription', 'Audio transcription')], help_text='Title for Services section [English]', max_length=255, null=True)),
                ('service_two_title_ar', models.CharField(choices=[('تصميم الغلاف', 'تصميم الغلاف'), ('تنسيق الكتاب', 'تنسيق الكتاب'), ('السترجة', 'السترجة'), ('النسخ الصوتى', 'النسخ الصوتى')], help_text='Title for Services section  [Arabic]', max_length=255, null=True)),
                ('service_two_summary_en', ckeditor.fields.RichTextField(help_text='Summary Services section [English]', null=True)),
                ('service_two_summary_ar', ckeditor.fields.RichTextField(help_text='Summary for Services section  [Arabic]', null=True)),
                ('service_three_title_en', models.CharField(choices=[('Cover design', 'Cover design'), ('Book format', 'Book format'), ('Subtraction', 'Subtraction'), ('Audio transcription', 'Audio transcription')], help_text='Title for Services section [English]', max_length=255, null=True)),
                ('service_three_title_ar', models.CharField(choices=[('تصميم الغلاف', 'تصميم الغلاف'), ('تنسيق الكتاب', 'تنسيق الكتاب'), ('السترجة', 'السترجة'), ('النسخ الصوتى', 'النسخ الصوتى')], help_text='Title for Services section  [Arabic]', max_length=255, null=True)),
                ('service_three_summary_en', ckeditor.fields.RichTextField(help_text='Summary Services section [English]', null=True)),
                ('service_three_summary_ar', ckeditor.fields.RichTextField(help_text='Summary for Services section  [Arabic]', null=True)),
                ('service_four_title_en', models.CharField(choices=[('Cover design', 'Cover design'), ('Book format', 'Book format'), ('Subtraction', 'Subtraction'), ('Audio transcription', 'Audio transcription')], help_text='Title for Services section [English]', max_length=255, null=True)),
                ('service_four_title_ar', models.CharField(choices=[('تصميم الغلاف', 'تصميم الغلاف'), ('تنسيق الكتاب', 'تنسيق الكتاب'), ('السترجة', 'السترجة'), ('النسخ الصوتى', 'النسخ الصوتى')], help_text='Title for Services section  [Arabic]', max_length=255, null=True)),
                ('service_four_summary_en', ckeditor.fields.RichTextField(help_text='Summary Services section [English]', null=True)),
                ('service_four_summary_ar', ckeditor.fields.RichTextField(help_text='Summary for Services section  [Arabic]', null=True)),
                ('contact_title_en', models.CharField(help_text='Title for Contact section [English]', max_length=255, null=True)),
                ('address_en', ckeditor.fields.RichTextField(help_text='Address Contact section [English]', null=True)),
                ('contact_title_ar', models.CharField(help_text='Title for Contact section [Arabic]', max_length=255, null=True)),
                ('address_ar', ckeditor.fields.RichTextField(help_text='Address Contact section [Arabic]', null=True)),
                ('phone_nashr', models.CharField(help_text='Phone Number for Contact section [Arabic]', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
