# Generated by Django 4.0.1 on 2022-02-07 16:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_about_goals_sub_ar_remove_about_goals_sub_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='phone_nashr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_four_summary_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_four_summary_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_four_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_four_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_one_summary_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_one_summary_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_one_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_one_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_three_summary_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_three_summary_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_three_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_three_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_two_summary_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_two_summary_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_two_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_two_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_btn_txt_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_btn_txt_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_sub_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='what_we_offer_sub_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_section_Service_title_ar',
            field=models.CharField(blank=True, help_text='title For Service for Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_services_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_sub_heading_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for service section [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_section_Service_title_ar',
            field=models.CharField(blank=True, help_text='title For Service for Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_services_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fourth_sub_heading_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for service section [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_ar',
            field=models.CharField(blank=True, help_text='Heading for Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_en',
            field=models.CharField(blank=True, help_text='Heading for Home Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_section_Service_title_ar',
            field=models.CharField(blank=True, help_text='title For Service for Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_services_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_sub_heading_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for service section [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_heading_ar',
            field=models.CharField(blank=True, help_text='Heading for Service Section Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_heading_en',
            field=models.CharField(blank=True, help_text='Heading for Service Section Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_sub_heading_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for Services Home Page [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_sub_heading_en',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for Services Home Page [English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for Home Page [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_en',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for Home Page [English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_subsraction_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for Home Page [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_subsraction_en',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for Home Page [English]', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='substraction_heading_ar',
            field=models.CharField(blank=True, help_text='substraction Heading for Home Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_section_Service_title_ar',
            field=models.CharField(blank=True, help_text='title For Service for Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_services_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_sub_heading_ar',
            field=ckeditor.fields.RichTextField(help_text='sub Heading for service section [Arabic]', null=True),
        ),
    ]
