# Generated by Django 4.0.1 on 2022-02-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homepage_first_section_service_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='substraction_heading_en',
            field=models.CharField(blank=True, help_text='title For Substraction for Home Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='substraction_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
