# Generated by Django 4.0.1 on 2022-02-07 17:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homepage_substraction_heading_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='whous',
            name='goals_heading_ar',
            field=models.CharField(help_text='Title for goals Section [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='goals_heading_en',
            field=models.CharField(help_text='Title for goals Section [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='roaya_content_ar',
            field=ckeditor.fields.RichTextField(help_text='Content for Who Us Page [English]', null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='roaya_content_en',
            field=ckeditor.fields.RichTextField(help_text='Content for Who Us Page [English]', null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='roaya_heading_ar',
            field=models.CharField(help_text='Title for Roaya Section [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='roaya_heading_en',
            field=models.CharField(help_text='Title for Roaya Section [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='roaya_sub_ar',
            field=models.CharField(help_text='SubTitle for Roaya Section [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='roaya_sub_en',
            field=models.CharField(help_text='SubTitle for Roaya Section [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='section_goals_ar',
            field=ckeditor.fields.RichTextField(help_text='Section for goals Page [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='whous',
            name='section_goals_en',
            field=ckeditor.fields.RichTextField(help_text='Section for goals Page [English]', null=True),
        ),
        migrations.AlterField(
            model_name='whous',
            name='content_ar',
            field=ckeditor.fields.RichTextField(help_text='Content for Who Us Page [Arabic]', null=True),
        ),
        migrations.AlterField(
            model_name='whous',
            name='content_en',
            field=ckeditor.fields.RichTextField(help_text='Content for Who Us Page [English]', null=True),
        ),
    ]
