# Generated by Django 4.0.1 on 2022-02-08 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_about_whous_goals_heading_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_five_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_five_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_four_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_four_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_one_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_one_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_seven_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_seven_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_six_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_six_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_three_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_three_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_two_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='section_two_en',
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='first_rule_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='first_rule_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='join_content_ar',
            field=ckeditor.fields.RichTextField(help_text='How To Join Content for MemberShipTerms Page [Arabic]', null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='join_content_en',
            field=ckeditor.fields.RichTextField(help_text='How To Join Content for MemberShipTerms Page [English]', null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='join_head_ar',
            field=models.CharField(blank=True, help_text='How To Join Title for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='join_head_en',
            field=models.CharField(blank=True, help_text='How To Join Title for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='second_rule_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='second_rule_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='sub_first_rule_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='sub_first_rule_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='sub_second_rule_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='sub_second_rule_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='sub_third_rule_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='sub_third_rule_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='third_rule_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='third_rule_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
    ]
