# Generated by Django 4.0.1 on 2022-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_membershipterms_section_five_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipterms',
            old_name='heading_ar',
            new_name='book_heading_ar',
        ),
        migrations.RenameField(
            model_name='membershipterms',
            old_name='heading_en',
            new_name='book_heading_en',
        ),
        migrations.RenameField(
            model_name='membershipterms',
            old_name='sub_heading_en',
            new_name='book_sub_heading_en',
        ),
        migrations.RenameField(
            model_name='membershipterms',
            old_name='sub_heading_ar',
            new_name='translator_sub_heading_ar',
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='translator_heading_ar',
            field=models.CharField(help_text='Title for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='translator_heading_en',
            field=models.CharField(help_text='Title for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipterms',
            name='translator_sub_heading_en',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True),
        ),
    ]
