# Generated by Django 4.0.1 on 2022-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_heading_ar_membershipterms_book_heading_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipterms',
            name='book_sub_heading_ar',
            field=models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True),
        ),
    ]
