# Generated by Django 4.0.1 on 2022-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_membershipterms_book_sub_heading_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homepage_background',
            field=models.ImageField(null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='whous',
            name='whous_background',
            field=models.ImageField(null=True, upload_to='backgrounds/'),
        ),
    ]
