# Generated by Django 4.0.1 on 2022-02-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_homepage_homepage_background_whous_whous_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipterms',
            name='book_heading_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='book_heading_en',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='book_sub_heading_ar',
        ),
        migrations.RemoveField(
            model_name='membershipterms',
            name='book_sub_heading_en',
        ),
    ]
