# Generated by Django 4.0.1 on 2022-02-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_membershipterms_book_heading_ar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipTerms',
            new_name='TranslatorMembershipTerms',
        ),
    ]
