# Generated by Django 4.0.1 on 2022-02-08 17:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_membershipterms_translatormembershipterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_ar', models.CharField(blank=True, help_text='Heading for Home Page [Arabic]', max_length=255, null=True)),
                ('heading_en', models.CharField(blank=True, help_text='Heading for Home Page [English]', max_length=255, null=True)),
                ('sub_heading_ar', ckeditor.fields.RichTextField(help_text='sub Heading for Home Page [Arabic]', null=True)),
                ('sub_heading_en', ckeditor.fields.RichTextField(help_text='sub Heading for Home Page [English]', null=True)),
                ('roles_heading_ar', models.CharField(blank=True, help_text='Heading for Home Page [Arabic]', max_length=255, null=True)),
                ('roles_heading_en', models.CharField(blank=True, help_text='Heading for Home Page [English]', max_length=255, null=True)),
                ('roles_content_en', ckeditor.fields.RichTextField(help_text='Content For Roles [English', null=True)),
                ('roles_content_ar', ckeditor.fields.RichTextField(help_text='Content For Roles [Arabic', null=True)),
                ('sub_first_rule_en', models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True)),
                ('sub_first_rule_ar', models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True)),
                ('second_rule_en', models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True)),
                ('second_rule_ar', models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True)),
                ('sub_second_rule_en', models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True)),
                ('sub_second_rule_ar', models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True)),
                ('third_rule_en', models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True)),
                ('third_rule_ar', models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True)),
                ('sub_third_rule_en', models.CharField(help_text='SubTitle for MemberShipTerms Page [English]', max_length=255, null=True)),
                ('sub_third_rule_ar', models.CharField(help_text='SubTitle for MemberShipTerms Page [Arabic]', max_length=255, null=True)),
                ('join_head_ar', models.CharField(blank=True, help_text='How To Join Title for MemberShipTerms Page [Arabic]', max_length=255, null=True)),
                ('join_head_en', models.CharField(blank=True, help_text='How To Join Title for MemberShipTerms Page [English]', max_length=255, null=True)),
                ('join_content_ar', ckeditor.fields.RichTextField(help_text='How To Join Content for MemberShipTerms Page [Arabic]', null=True)),
                ('join_content_en', ckeditor.fields.RichTextField(help_text='How To Join Content for MemberShipTerms Page [English]', null=True)),
            ],
        ),
    ]
