# Generated by Django 4.0.1 on 2022-02-21 20:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_publishingbook_first_rule_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('question_en', models.CharField(blank=True, help_text='question for FAQ Page [English]', max_length=255, null=True)),
                ('question_ar', models.CharField(blank=True, help_text='question for FAQ Page [Arabic]', max_length=255, null=True)),
                ('answer_en', ckeditor.fields.RichTextField(help_text='Answer for question  [English]')),
                ('answer_ar', ckeditor.fields.RichTextField(help_text='Answer for question  [Arabic]')),
                ('home_page_show', models.BooleanField(default=False, help_text='Appear in home Page [Arabic]')),
            ],
        ),
    ]
