# Generated by Django 4.0.1 on 2022-02-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='substraction_heading_ar',
            field=models.CharField(blank=True, help_text='Substraction Heading for Home Page [Arabic]', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='substraction_heading_en',
            field=models.CharField(blank=True, help_text='substraction Heading for Home Page [English]', max_length=255, null=True),
        ),
    ]
