# Generated by Django 4.0.1 on 2022-03-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_book_option_book_dropbox_link'),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('number_of_colors', models.IntegerField(blank=True, null=True)),
                ('number_of_copies', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
            ],
        ),
    ]
