# Generated by Django 4.0.1 on 2022-03-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_printbookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='printbookrequest',
            name='paper_size',
            field=models.CharField(blank=True, choices=[('A5', 'A5'), ('A4', 'A4')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printbookrequest',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('عادى', 'عادى'), ('لماع', 'لماع'), ('لاصق', 'لاصق'), ('مقوى', 'مقوى')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printbookrequest',
            name='print_color',
            field=models.CharField(blank=True, choices=[('أسود', 'أسود'), ('ملون', 'ملون')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printbookrequest',
            name='print_face',
            field=models.CharField(blank=True, choices=[('وجه واحد', 'وجة واحد'), ('وجهين ', 'وجهين ')], max_length=255, null=True),
        ),
    ]
