# Generated by Django 4.0.1 on 2022-03-23 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_negotiation_is_accepted_negotiationbook_is_accepted'),
        ('designs', '0005_bookformating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookformating',
            name='book_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
